djangoclassification/app_cancer/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from app_cancer.views import LungCancerView, LungCancerEdit, LungCancerDelete

urlpatterns = [
    path('', RedirectView.as_view(url='list/'), name='index'),
    path('list/', LungCancerView.as_view(), name='list'),
    path('register/', views.LungCancerRegister.as_view(), name='register'),
    path('edit/<int:id>/', LungCancerEdit.as_view(), name='edit'),
    path('delete/<int:id>/', LungCancerDelete.as_view(), name='delete'),

    path('grafico_resultados', views.grafico_resultados, name='grafico_resultados'),
    path('grafico_casos_por_genero', views.grafico_casos_por_genero, name='grafico_casos_por_genero'),
    path('grafico_idade', views.grafico_idade, name='grafico_idade'),
    path('grafico_fumantes_cancer', views.grafico_fumantes_cancer, name='grafico_fumantes_cancer'),
    
    
] 

djangoclassification/djangoclassification/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

djangoclassification/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_cancer.urls')),
] 

djangoclassification/app_cancer/models.py
from django.db import models

class LungCancer(models.Model):
    age = models.IntegerField(null=True, blank=True)
    gender = models.IntegerField(choices=[(0, 'Feminino'), (1, 'Masculino')], null=True, blank=True)
    smoking = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    finger_discoloration = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    mental_stress = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    exposure_to_pollution = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    long_term_illness = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    energy_level = models.FloatField(null=True, blank=True)
    immune_weakness = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    breathing_issue = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    alcohol_consumption = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    throat_discomfort = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    oxygen_saturation = models.FloatField(null=True, blank=True)
    chest_tightness = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    family_history = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    smoking_family_history = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    stress_immune = models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], null=True, blank=True)
    resultado = models.CharField(max_length=20, null=True, blank=True)
            
def __str__(self):
    gender = dict(self.GENDER_CHOICES).get(self.gender, 'Indefinido')
    smoking = dict(self.SMOKING_CHOICES).get(self.smoking, 'Indefinido')
    return f'Paciente {self.id} - Idade: {self.age} - Gênero: {gender} - Fumante: {smoking}'

djangoclassification/app_cancer/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from django.conf import settings
from .models import LungCancer
import app_cancer.models as ControlModels
import os
import pickle
from django.shortcuts import render
from .models import LungCancer
from django.http import HttpResponse
from io import BytesIO
import matplotlib.pyplot as plt
from .models import LungCancer
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

matplotlib.use('Agg') 

def load_model():
    path = os.path.join(settings.BASE_DIR, 'ml', 'model.pkl')
    with open(path, 'rb') as f:
        return pickle.load(f)

model = load_model()


class LungCancerView(View):
    def get(self, request, *args, **kwargs):
        data = ControlModels.LungCancer.objects.all().order_by('id')
        paginator = Paginator(data, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'index.html', {"page_obj": page_obj})
    
class LungCancerRegister(View):
    def get(self, request, *args, **kwargs):
        return render(request, '../templates/forms.html')
    
    @method_decorator(csrf_protect)
    def post(self, request, *args, **kwargs):
        data_array = self._extract_form_data(request)
        prediction = model.predict([data_array])[0]
        resultado = 'Com câncer' if prediction == 1 else 'Sem câncer'

        ControlModels.LungCancer.objects.create(
                    age=data_array[1],
                    gender=data_array[0],
                    smoking=data_array[2],
                    finger_discoloration=data_array[3],
                    mental_stress=data_array[4],
                    exposure_to_pollution=data_array[5],
                    long_term_illness=data_array[6],
                    energy_level=data_array[7],
                    immune_weakness=data_array[8],
                    breathing_issue=data_array[9],
                    alcohol_consumption=data_array[10],
                    throat_discomfort=data_array[11],
                    oxygen_saturation=data_array[12],
                    chest_tightness=data_array[13],
                    family_history=data_array[14],
                    smoking_family_history=data_array[15],
                    stress_immune=data_array[16],
                    resultado=resultado
                )
            
        return render(request, '../templates/forms.html', {'resultado': resultado})

    def _extract_form_data(self, request):
        return [
            request.POST.get('gender'),
            request.POST.get('age'),
            request.POST.get('smoking'),
            request.POST.get('finger_discoloration'),
            request.POST.get('mental_stress'),
            request.POST.get('exposure_to_pollution'),
            request.POST.get('long_term_illness'),
            request.POST.get('energy_level'),
            request.POST.get('immune_weakness'),
             request.POST.get('breathing_issue'),
            request.POST.get('alcohol_consumption'),
            request.POST.get('throat_discomfort'),
            request.POST.get('oxygen_saturation'),
            request.POST.get('chest_tightness'),
            request.POST.get('family_history'),
            request.POST.get('smoking_family_history'),
            request.POST.get('stress_immune')
        ]
    

class LungCancerEdit(View):
    @method_decorator(csrf_protect)
    def get(self, request, id, *args, **kwargs):
        data = LungCancer.objects.get(id=id)
        return render(request, 'edit.html', {'data': data})
    
    @method_decorator(csrf_protect)
    def extract_form_data(self, request):
        data = [
            request.POST.get('gender'),
            request.POST.get('age'),
            request.POST.get('smoking'),
            request.POST.get('finger_discoloration'),
            request.POST.get('mental_stress'),
            request.POST.get('exposure_to_pollution'),
            request.POST.get('long_term_illness'),
            request.POST.get('energy_level'),
            request.POST.get('immune_weakness'),
            request.POST.get('breathing_issue'),
            request.POST.get('alcohol_consumption'),
            request.POST.get('throat_discomfort'),
            request.POST.get('oxygen_saturation'),
            request.POST.get('chest_tightness'),
            request.POST.get('family_history'),
            request.POST.get('smoking_family_history'),
            request.POST.get('stress_immune')
        ]
        return data

    @method_decorator(csrf_protect)
    def post(self, request, *args, **kwargs):
        data_array = self.extract_form_data(request)

        prediction = model.predict([data_array])[0]
        resultado = 'Com câncer' if prediction == 1 else 'Sem câncer'

        lung_cancer_instance = ControlModels.LungCancer.objects.get(id=request.POST.get('id'))

        lung_cancer_instance.gender = data_array[0]
        lung_cancer_instance.age = data_array[1]
        lung_cancer_instance.smoking = data_array[2]
        lung_cancer_instance.finger_discoloration = data_array[3]
        lung_cancer_instance.mental_stress = data_array[4]
        lung_cancer_instance.exposure_to_pollution = data_array[5]
        lung_cancer_instance.long_term_illness = data_array[6]
        lung_cancer_instance.energy_level = data_array[7]
        lung_cancer_instance.immune_weakness = data_array[8]
        lung_cancer_instance.breathing_issue = data_array[9]
        lung_cancer_instance.alcohol_consumption = data_array[10]
        lung_cancer_instance.throat_discomfort = data_array[11]
        lung_cancer_instance.oxygen_saturation = data_array[12]
        lung_cancer_instance.chest_tightness = data_array[13]
        lung_cancer_instance.family_history = data_array[14]
        lung_cancer_instance.smoking_family_history = data_array[15]
        lung_cancer_instance.stress_immune = data_array[16]
        lung_cancer_instance.resultado = resultado

        lung_cancer_instance.save()

        return render(request, 'edit.html', {'data': lung_cancer_instance, 'resultado': resultado})


class LungCancerDelete(View):
    def post(self, request, id):
        data = LungCancer.objects.get(id=id)
        data.delete() 

        return redirect('list')
    
def grafico_resultados(request):
    dataset = LungCancer.objects.all()

    resultados = {}
    for record in dataset:
        resultado = record.resultado 
        resultados[resultado] = resultados.get(resultado, 0) + 1

    labels = list(resultados.keys())
    sizes = list(resultados.values())

    plt.figure(figsize=(8, 8))
    plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140)
    
    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    plt.close()

    return HttpResponse(buffer, content_type='image/png')

def grafico_fumantes_cancer(request):
    pacientes = LungCancer.objects.filter(resultado="Com câncer")

    contagem = {'Fumantes': 0, 'Não Fumantes': 0}
    for paciente in pacientes:
        if paciente.smoking == 1:
            contagem['Fumantes'] += 1
        elif paciente.smoking == 0:
            contagem['Não Fumantes'] += 1

    labels = list(contagem.keys())
    valores = list(contagem.values())

    plt.figure(figsize=(8, 8))
    plt.pie(valores, labels=labels, autopct='%1.1f%%', startangle=140)

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    plt.close()

    return HttpResponse(buffer, content_type='image/png')

def grafico_casos_por_genero(request):
    dataset = LungCancer.objects.filter(resultado="Com câncer")

    resultados = {}
    for record in dataset:
        genero = record.get_gender_display()  
        resultados[genero] = resultados.get(genero, 0) + 1

    labels = list(resultados.keys())
    sizes = list(resultados.values())

    cores = []
    for genero in labels:
        if genero == 'Masculino':
            cores.append('RoyalBlue')  
        elif genero == 'Feminino':
            cores.append('hotpink')    
        else:
            cores.append('gray') 

    plt.figure(figsize=(8, 6))
    plt.bar(labels, sizes, color=cores)
    plt.xlabel('Gênero')
    plt.ylabel('Quantidade de Registros')

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    plt.close()

    return HttpResponse(buffer, content_type='image/png')

def grafico_idade(request):
    dataset = LungCancer.objects.filter(resultado="Com câncer")

    idades = [record.age for record in dataset if record.age is not None]

    plt.figure(figsize=(8, 6))
    plt.hist(idades, bins=10, color='mediumslateblue', edgecolor='black')
    plt.xlabel('Idade')
    plt.ylabel('Número de Pacientes')

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    plt.close()

    return HttpResponse(buffer, content_type='image/png')

djangoclassification/app_cancer/templates/edit.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário de Previsão</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
        }

        h2 {
            text-align: center;
            color: #333;
            margin-top: 20px;
        }

        .form-container {
            width: 60%;
            margin: 0 auto;
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        table {
            width: 100%;
            margin-top: 20px;
        }

        td {
            padding: 10px;
            text-align: left;
        }

        label {
            font-size: 16px;
            color: #555;
        }

        input[type="number"], input[type="radio"] {
            margin-top: 5px;
        }

        button {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            border-radius: 4px;
            transition: background-color 0.3s;
        }

        button:hover {
            background-color: #45a049;
        }

        .back-btn {
            margin-top: 20px;
            display: block;
            text-align: center;
            font-size: 16px;
            color: #333;
            text-decoration: none;
            padding: 10px;
            background-color: #ccc;
            border-radius: 4px;
        }

        .back-btn:hover {
            background-color: #bbb;
        }
    </style>
</head>
<body>
    <h2>Predição de Câncer de Pulmão</h2>
    <div class="form-container">
        <form method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <tr>
                        <td><label for="id">Id:</label></td>
                        <td><input type="number" name="id" id="id" value="{{ data.id }}" required readonly></td>
                    </tr>
                    <td><label for="gender">Gênero:</label></td>
                    <td>
                        <input type="radio" name="gender" value="0" id="gender-f" {% if data.gender == 0 %}checked{% endif %} required><label for="gender-f">Feminino</label>
                        <input type="radio" name="gender" value="1" id="gender-m" {% if data.gender == 1 %}checked{% endif %}><label for="gender-m">Masculino</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="age">Idade:</label></td>
                    <td><input type="number" name="age" id="age" value="{{ data.age }}" required></td>
                </tr>
                <tr>
                    <td><label for="smoking">Fuma?</label></td>
                    <td>
                        <input type="radio" name="smoking" value="0" id="smoking-no" {% if data.smoking == 0 %}checked{% endif %} required><label for="smoking-no">Não</label>
                        <input type="radio" name="smoking" value="1" id="smoking-yes" {% if data.smoking == 1 %}checked{% endif %}><label for="smoking-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="finger_discoloration">Descoloração dos dedos?</label></td>
                    <td>
                        <input type="radio" name="finger_discoloration" value="0" id="finger_discoloration-no" {% if data.finger_discoloration == 0 %}checked{% endif %} required><label for="finger_discoloration-no">Não</label>
                        <input type="radio" name="finger_discoloration" value="1" id="finger_discoloration-yes" {% if data.finger_discoloration == 1 %}checked{% endif %}><label for="finger_discoloration-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="mental_stress">Estresse mental?</label></td>
                    <td>
                        <input type="radio" name="mental_stress" value="0" id="mental_stress-no" {% if data.mental_stress == 0 %}checked{% endif %} required><label for="mental_stress-no">Não</label>
                        <input type="radio" name="mental_stress" value="1" id="mental_stress-yes" {% if data.mental_stress == 1 %}checked{% endif %}><label for="mental_stress-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="exposure_to_pollution">Exposição à poluição?</label></td>
                    <td>
                        <input type="radio" name="exposure_to_pollution" value="0" id="exposure_to_pollution-no" {% if data.exposure_to_pollution == 0 %}checked{% endif %} required><label for="exposure_to_pollution-no">Não</label>
                        <input type="radio" name="exposure_to_pollution" value="1" id="exposure_to_pollution-yes" {% if data.exposure_to_pollution == 1 %}checked{% endif %}><label for="exposure_to_pollution-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="long_term_illness">Doença de longo prazo?</label></td>
                    <td>
                        <input type="radio" name="long_term_illness" value="0" id="long_term_illness-no" {% if data.long_term_illness == 0 %}checked{% endif %} required><label for="long_term_illness-no">Não</label>
                        <input type="radio" name="long_term_illness" value="1" id="long_term_illness-yes" {% if data.long_term_illness == 1 %}checked{% endif %}><label for="long_term_illness-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="energy_level">Nível de energia baixo (0 a 100):</label></td>
                    <td><input type="number" name="energy_level" id="energy_level" value="{{ data.energy_level }}" required></td>
                </tr>
                <tr>
                    <td><label for="immune_weakness">Fraqueza imunológica?</label></td>
                    <td>
                        <input type="radio" name="immune_weakness" value="0" id="immune_weakness-no" {% if data.immune_weakness == 0 %}checked{% endif %} required><label for="immune_weakness-no">Não</label>
                        <input type="radio" name="immune_weakness" value="1" id="immune_weakness-yes" {% if data.immune_weakness == 1 %}checked{% endif %}><label for="immune_weakness-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="breathing_issue">Dificuldade para respirar?</label></td>
                    <td>
                        <input type="radio" name="breathing_issue" value="0" id="breathing_issue-no" {% if data.breathing_issue == 0 %}checked{% endif %} required><label for="breathing_issue-no">Não</label>
                        <input type="radio" name="breathing_issue" value="1" id="breathing_issue-yes" {% if data.breathing_issue == 1 %}checked{% endif %}><label for="breathing_issue-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="alcohol_consumption">Consumo de álcool?</label></td>
                    <td>
                        <input type="radio" name="alcohol_consumption" value="0" id="alcohol_consumption-no" {% if data.alcohol_consumption == 0 %}checked{% endif %} required><label for="alcohol_consumption-no">Não</label>
                        <input type="radio" name="alcohol_consumption" value="1" id="alcohol_consumption-yes" {% if data.alcohol_consumption == 1 %}checked{% endif %}><label for="alcohol_consumption-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="throat_discomfort">Desconforto na garganta?</label></td>
                    <td>
                        <input type="radio" name="throat_discomfort" value="0" id="throat_discomfort-no" {% if data.throat_discomfort == 0 %}checked{% endif %} required><label for="throat_discomfort-no">Não</label>
                        <input type="radio" name="throat_discomfort" value="1" id="throat_discomfort-yes" {% if data.throat_discomfort == 1 %}checked{% endif %}><label for="throat_discomfort-yes">Sim</label>
                    </td>
                </tr>
                <tr>
                    <td><label for="oxygen_saturation">Saturação de oxigênio:</label></td>
                    <td><input type="number" name="oxygen_saturation" id="oxygen_saturation" value="{{ data.oxygen_saturation }}" required></td>
                </tr>
            </table>
            <button type="submit">Salvar</button>
        </form>
        <a href="/" class="back-btn">Voltar</a>

        <div style="margin-top: 20px;">
            <strong>Resultado:</strong> {{ resultado }}
        </div>
    
    </div>
</body>
</html>

djangoclassification/app_cancer/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Previsor de Câncer de Pulmão</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 20px;
        }

        h2 {
            margin-top: 40px;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 20px;
        }

        table, th, td {
            border: 1px solid #ccc;
        }

        th, td {
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }

        .pagination {
            margin-top: 20px;
        }

        .pagination a {
            margin: 0 5px;
            text-decoration: none;
            color: blue;
        }

        .pagination .current {
            margin: 0 10px;
            font-weight: bold;
        }

        button {
            padding: 8px 12px;
            background-color: #007BFF;
            border: none;
            color: white;
            cursor: pointer;
            border-radius: 4px;
        }

        button:hover {
            background-color: #0056b3;
        }

        .delete-button {
            background-color: #FF4B4B;
        }

        .delete-button:hover {
            background-color: #D94343;
        }

        .grafico-container {
            display: flex;
            justify-content: space-between;
            gap: 20px;
            flex-wrap: wrap;  /* Isso vai garantir que, se a tela for pequena, os gráficos se movam para a linha de baixo */
        }

        .grafico {
            width: 48%;  /* Ajusta o tamanho de cada gráfico, dois gráficos vão ocupar 100% da largura */
            min-width: 300px;  /* Para garantir que os gráficos não fiquem muito pequenos */
            text-align: center;
        }

        img {
            width: 100%;  /* Faz os gráficos se ajustarem ao tamanho do contêiner */
            border-radius: 8px;  /* Para dar um toque mais estiloso */
        }

        /* Resposta para telas pequenas */
        @media (max-width: 768px) {
            .grafico {
                width: 100%;  /* Em telas pequenas, cada gráfico vai ocupar toda a largura */
            }
        }
    </style>
</head>
<body>

    <h2>Listagem de Dados</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Idade</th>
                <th>Gênero</th>
                <th>Fumante</th>
                <th>Descoloração dos dedos</th>
                <th>Estresse mental</th>
                <th>Exposição à poluição</th>
                <th>Doença de longo prazo</th>
                <th>Nível de energia</th>
                <th>Imunidade fraca</th>
                <th>Problema respiratório</th>
                <th>Consumo de álcool</th>
                <th>Desconforto na garganta</th>
                <th>Saturação de oxigênio</th>
                <th>Aperto no peito</th>
                <th>Histórico familiar</th>
                <th>Histórico de fumo na família</th>
                <th>Estresse + imunidade fraca</th>
                <th>Resultado</th>
                <th>Editar</th>
                <th>Excluir</th>
            </tr>
        </thead>
        <tbody>
            {% for data in page_obj %}
            <tr>
                <td>{{ data.id }}</td>
                <td>{{ data.age }}</td>
                <td>{{ data.get_gender_display }}</td>
                <td>{{ data.get_smoking_display }}</td>
                <td>{{ data.get_finger_discoloration_display }}</td>
                <td>{{ data.get_mental_stress_display }}</td>
                <td>{{ data.get_exposure_to_pollution_display }}</td>
                <td>{{ data.get_long_term_illness_display }}</td>
                <td>{{ data.energy_level }}</td>
                <td>{{ data.get_immune_weakness_display }}</td>
                <td>{{ data.get_breathing_issue_display }}</td>
                <td>{{ data.get_alcohol_consumption_display }}</td>
                <td>{{ data.get_throat_discomfort_display }}</td>
                <td>{{ data.oxygen_saturation }}</td>
                <td>{{ data.get_chest_tightness_display }}</td>
                <td>{{ data.get_family_history_display }}</td>
                <td>{{ data.get_smoking_family_history_display }}</td>
                <td>{{ data.get_stress_immune_display }}</td>
                <td>{{ data.resultado }}</td>
                <td>
                    <form method="get" action="/edit/{{ data.id }}/">
                        {% csrf_token %}
                        <button type="submit">Editar</button>
                    </form>
                </td>
                <td>
                    <form method="post" action="/delete/{{ data.id }}/">
                        {% csrf_token %}
                        <button type="submit" class="delete-button">Excluir</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="20">Nenhum dado encontrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Primeiro</a>
                <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
            {% endif %}

            <span class="current">
                Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
            {% endif %}
        </span>
    </div>

    <button onclick="window.location.href = '{% url 'register' %}'">Novo Registro</button>

    <h2>Dashboard - Câncer de Pulmão</h2>

    <div class="grafico-container">
        <div class="grafico">
            <h3>Porcentagem dos resultados</h3>
            <img src="{% url 'grafico_resultados' %}" alt="Proporção dos Resultados">
        </div>

        <div class="grafico">
            <h3>Comparação de Câncer entre fumantes e não fumantes</h3>
            <img src="{% url 'grafico_fumantes_cancer' %}" alt="grafico_fuamntes_cancer">
        </div>

        <div class="grafico">
            <h3>Comparação de pacientes com Câncer por Gênero</h3>
            <img src="{% url 'grafico_casos_por_genero' %}" alt="Gráfico por Gênero">
        </div>

        <div class="grafico">
            <h3>Histograma de pacientes com Câncer</h3>
            <img src="{% url 'grafico_idade' %}" alt="grafico_idade">
        </div>
    </div>
</body>
</html>